name: ${pluginName}
version: $version
main: $group.${rootProject.name}.plugin.${pluginName}Plugin
api-version: 1.17
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.21
  - org.jetbrains.kotlin:kotlin-reflect:1.5.21
  - io.github.monun:invfx:3.0.0
commands:
  test2: